# Generated by Django 5.1.1 on 2024-11-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('active', 'Active'), ('completed', 'Completed')], default='started', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest_rate_on_late_payments', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delinquent_payments', models.IntegerField(default=0)),
                ('number_of_payments', models.IntegerField()),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Products', models.ManyToManyField(related_name='credits', to='products.product')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_in', models.DateTimeField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.credit')),
            ],
        ),
    ]
